config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'devices#index'
  post '/upload', to: 'devices#proces_csv', as: 'upload'
  get '/device_history', to: 'devices#device_history', as: 'device_history'

  # This route was made for testing purposes
  # get '/new_csv', to: 'devices#new_csv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
require "csv"
class Device < ApplicationRecord
  validates :timestamp,            presence: true
  validates :device_serial_number, presence: true
  validates :device_type,          presence: true
  validates :status,               presence: true

  validates :device_type,          inclusion: { in: %w[gateway sensor] }
  validates :status,               inclusion: { in: %w[online offline] }

  scope :in_day, ->(day) { where("timestamp >= ? AND timestamp <= ?", "#{day} 00:00:00", "#{day} 23:59:59") }
  scope :type_and_status, ->(type, status) { where("device_type = ? AND status = ?", type, status) }
  scope :match_serial, ->(serial) { where("device_serial_number = ?", serial) }

  def self.get_devices(day)
    Device.in_day(day).group(:device_serial_number)
          .count.sort_by { |_key, value| value * -1 }
          .first(10)
  end

  def self.get_types(day, type, status)
    devices = Device.in_day(day).type_and_status(type, status)
    return 0 if devices.empty?

    devices.map { |device| device }.uniq!(&:device_serial_number).count
  end

  def self.create_records(file)
    csv_options = { col_sep: ',', quote_char: '"', headers: :first_row }
    csv_file = CSV.parse(file.read, csv_options)
    csv_file.each do |row|
      Device.create(
        timestamp: row['timestamp'],
        device_serial_number: row['id'],
        device_type: row['type'],
        status: row['status']
      )
    end
  end

  def find_percentage(day, occurrence)
    day = (day.to_date - 7).to_s
    prev_occurrence = Device.in_day(day).match_serial(device_serial_number).count
    calculate_percentage(prev_occurrence, occurrence)
  end

  private

  def calculate_percentage(prev_o, occurrence)
    return "No previous record" if prev_o.zero?

    "#{((occurrence * 100) / prev_o) - 100}%"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_token_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[proces_csv]
  before_action :authenticate_user!, only: %i[index]

  def index
    return unless params[:device]

    @day = device_params[:timestamp]
    @devices = Device.get_devices(@day)
  end

  def device_history
    return unless params[:device]

    @day = device_params[:timestamp]
    @type = device_params[:device_type]
    @status = device_params[:status]
    @all_days = get_all_days([], @day, @status, @type)
  end

  def proces_csv
    if authenticate_user_key
      Device.create_records(params[:X_Upload_File])
      render :proces_csv, status: :created
    else
      render :error, status: :unauthorized
    end
  end

  private

  def get_all_days(all_days, day, status, type)
    all_days = all_days
    counter = 0
    30.times do
      @device_count = Device.get_types((day.to_date + counter).to_s, type, status)
      all_days << [@device_count, (day.to_date + counter).to_s]
      counter -= 1
    end
    all_days
  end

  def authenticate_user_key
    user  = User.find_by(email: params[:X_User_Email])
    token = params[:X_User_Token]
    return user.authentication_token == token if user

    false
  end

  def device_params
    params.require(:device).permit(:timestamp, :device_type, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/device_history.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="d-flex">
    <div class="left-screen sticky-t-56">
      <%= render 'devices/device_history_components/form', day: @day, all_days: @all_days %>
    </div>
    <% if params[:device].nil? %>
      <p class="text-info my-4 mx-3">Please select a date</p>
    <% elsif @all_days %>
      <%= render 'devices/device_history_components/table', all_days: @all_days %>
    <% else %>
      <p class="text-danger my-4 mx-3">Date is not valid</p>
    <% end %>
  </div>
</div>

app/views/devices/device_history_components/_form.html.erb
<form action="/device_history" class="search-form form-2 m-4">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group mb-2">
    <label for="device_timestamp">Select day</label>
    <% if all_days %>
        <input type="date" name="device[timestamp]" id="device_timestamp" class="form-control flatpickr" value=<%= day %>>
      <% else %>
        <input type="date" name="device[timestamp]" id="device_timestamp" class="form-control flatpickr">
      <% end %>
    <label for="device_typee">Select type</label>
    <select name="device[device_type]" id="device_typee" class="form-control">
      <option value="gateway" selected>Gateway</option>
      <option value="sensor">Sensor</option>
    </select>
  </div>
  <div class="form-group mb-2">
    <label for="device_statuss">Select status</label>
    <select name="device[status]" id="device_statuss" class="form-control">
      <option value="online"></option>
      <option value="online" selected>Online</option>
      <option value="offline">Offline</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary btn-lg btn-block">Go!</button>
</form>

app/views/devices/device_history_components/_table.html.erb
<table class="table m-3 table-hover">
  <thead class="thead-dark">
    <tr class="sticky-top">
      <th scope="col">Day</th>
      <th scope="col">Count</th>
    </tr>
  </thead>
  <% all_days.each do |count, date| %>
    <tbody>
      <tr>
        <!-- Puts date before day -->
        <td><%= date.to_date.strftime('%b %d, %A') %></td>
        <td><%= count %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/devices/error.json.erb
{ "status" : "Wrong username or key" }

app/views/devices/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="d-flex">
    <div class="left-screen sticky-t-56">
      <%= render 'devices/index_components/form', day: @day %>
      <div class="relative">
        <%= link_to "", device_history_path, class:"absolute-0-0" %>
        <button class="btn btn-secondary m-4">Devise history!</button>
      </div>
    </div>

    <% if @devices %>
      <% if @devices.empty? %>
        <p class="text-info m-4">No entries this day</p>
      <% else %>
        <%= render 'devices/index_components/table', devices: @devices, day:@day %>
      <% end %>
    <% else %>
      <p class="text-info my-4 mx-3">Please select a date</p>
    <% end %>
  </div>
</div>






<!-- Alternatives for form_with are form_for and simple_form which are
going to get deprecated soon.
Also, decided to write the form manually since I could not find a way to style
input helpers of form_with without sugesting me to change to form_for or simple
form. -->

<%#= form_with(url: root_path, method: 'get', class:"bg-primary") do %>
  <!-- <div class="form-group"> -->
      <%#= date_field(:device, :timestamp) %>
      <%#= submit_tag("Search!") %>
  <!-- </div> -->
<%# end %>

app/views/devices/index_components/_form.html.erb
<form action="/" class="search-form m-4">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="form-group" id="start">
      <label for="device_timestamp">Select day</label>
      <% if @devices %>
        <input required type="date" name="device[timestamp]" id="device_timestamp" class="form-control flatpickr" value=<%= day %>>
      <% else %>
        <input required type="date" name="device[timestamp]" id="device_timestamp" class="form-control flatpickr">
      <% end %>
    </div>
    <button type="submit" id="end" class="btn btn-primary btn-lg btn-block">Go!</button>
  </form>

app/views/devices/index_components/_table.html.erb
<table class="table m-3 b-shadow">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Popularity</th>
      <th scope="col">Device</th>
      <th scope="col">Type</th>
      <th scope="col">Ocurrence</th>
      <th scope="col">Growth</th>
    </tr>
  </thead>
  <tbody>
    <% counter = 1 %>
    <% devices.each do |device, occurrence| %>
      <% device = Device.find_by(device_serial_number: device) %>
      <tr>
        <th scope="row"><%= counter %></th>
        <td><%= device.device_serial_number %></td>
        <td><%= device.device_type.capitalize %></td>
        <td><%= occurrence %></td>
        <td><%= device.find_percentage(day, occurrence) %></td>
      </tr>
      <% counter += 1 %>
    <% end %>
  </tbody>
</table>

app/views/devices/new_csv.html.erb
<!-- this view was for testing purposes only -->

<!-- <h1>im really working</h1> -->

<%#= form_with(url: upload_path, method: 'post', multipart: true) do %>
  <%#= file_field_tag 'csv_file' %>
  <%#= submit_tag("Upload!") %>
<%# end %>

app/views/devices/proces_csv.json.erb
{ "status" : "csv succesfully loaded" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KiwiChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success fixed-bot"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger fixed-bot"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-info sticky-top">
  <div class="nav-lef d-flex">
    <%= link_to "Home", root_path, class:"mx-3 flex-center text-white decoration-none" %>
    <span class="navbar-brand mb-0 h1 text-white mx-3"><%= current_user.email %></span>
  </div>
  <span style="font-size: 17px" class="navbar-brand mb-0 h1 text-white">Key: <%= current_user.authentication_token %></span>
</nav>